[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# ДОБАВЬ СЕКЦИЮ ДЛЯ DEVNET:
[programs.devnet]
timelock_wallet = "CPPQFeBovJRCeLQ1Kh7HAX9qQMszh42XMBMpHMrrXBkD"

# ОСТАВЬ localnet для тестов:
[programs.localnet]
timelock_wallet = "3bL1e2w6nr2pg5RrPxdSAYw7bM9yFJ2mxW91Zrma62aF"

[registry]
url = "https://api.apr.dev"

# ИЗМЕНИ cluster на devnet:
[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""